<a href="https://colab.research.google.com/github/abhipsa079/Razorpay.github.io/blob/main/Copy_of_ANN_Template.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Deep Learning via ANN

## Importing libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [ ]:
tf.__version__

'2.12.0'

## Importing dataset

In [2]:
dataset = pd.read_csv('American Express User Exit Prediction.csv')
X = dataset.iloc[:, 0:-1].values
y = dataset.iloc[:, -1].values

In [ ]:
print(X)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

## Encoding categorical data

### Gender column : Label Encoding

In [3]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
X[:, 2] = label_encoder.fit_transform(X[:, 2])

In [ ]:
print(X)

[[ 5.1  3.5  4.   0.2]
 [ 4.9  3.   4.   0.2]
 [ 4.7  3.2  3.   0.2]
 [ 4.6  3.1  5.   0.2]
 [ 5.   3.6  4.   0.2]
 [ 5.4  3.9  7.   0.4]
 [ 4.6  3.4  4.   0.3]
 [ 5.   3.4  5.   0.2]
 [ 4.4  2.9  4.   0.2]
 [ 4.9  3.1  5.   0.1]
 [ 5.4  3.7  5.   0.2]
 [ 4.8  3.4  6.   0.2]
 [ 4.8  3.   4.   0.1]
 [ 4.3  3.   1.   0.1]
 [ 5.8  4.   2.   0.2]
 [ 5.7  4.4  5.   0.4]
 [ 5.4  3.9  3.   0.4]
 [ 5.1  3.5  4.   0.3]
 [ 5.7  3.8  7.   0.3]
 [ 5.1  3.8  5.   0.3]
 [ 5.4  3.4  7.   0.2]
 [ 5.1  3.7  5.   0.4]
 [ 4.6  3.6  0.   0.2]
 [ 5.1  3.3  7.   0.5]
 [ 4.8  3.4  8.   0.2]
 [ 5.   3.   6.   0.2]
 [ 5.   3.4  6.   0.4]
 [ 5.2  3.5  5.   0.2]
 [ 5.2  3.4  4.   0.2]
 [ 4.7  3.2  6.   0.2]
 [ 4.8  3.1  6.   0.2]
 [ 5.4  3.4  5.   0.4]
 [ 5.2  4.1  5.   0.1]
 [ 5.5  4.2  4.   0.2]
 [ 4.9  3.1  5.   0.1]
 [ 5.   3.2  2.   0.2]
 [ 5.5  3.5  3.   0.2]
 [ 4.9  3.1  5.   0.1]
 [ 4.4  3.   3.   0.2]
 [ 5.1  3.4  5.   0.2]
 [ 5.   3.5  3.   0.3]
 [ 4.5  2.3  3.   0.3]
 [ 4.4  3.2  3.   0.2]
 [ 5.   3.5

### Geography column : One hot Encoding

In [4]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [ ]:
print(X)

  (0, 14)	1.0
  (0, 23)	5.1
  (0, 24)	4.0
  (0, 25)	0.2
  (1, 9)	1.0
  (1, 23)	4.9
  (1, 24)	4.0
  (1, 25)	0.2
  (2, 11)	1.0
  (2, 23)	4.7
  (2, 24)	3.0
  (2, 25)	0.2
  (3, 10)	1.0
  (3, 23)	4.6
  (3, 24)	5.0
  (3, 25)	0.2
  (4, 15)	1.0
  (4, 23)	5.0
  (4, 24)	4.0
  (4, 25)	0.2
  (5, 18)	1.0
  (5, 23)	5.4
  (5, 24)	7.0
  (5, 25)	0.4
  (6, 13)	1.0
  :	:
  (143, 25)	2.3
  (144, 12)	1.0
  (144, 23)	6.7
  (144, 24)	33.0
  (144, 25)	2.5
  (145, 9)	1.0
  (145, 23)	6.7
  (145, 24)	28.0
  (145, 25)	2.3
  (146, 4)	1.0
  (146, 23)	6.3
  (146, 24)	26.0
  (146, 25)	1.9
  (147, 9)	1.0
  (147, 23)	6.5
  (147, 24)	28.0
  (147, 25)	2.0
  (148, 13)	1.0
  (148, 23)	6.2
  (148, 24)	30.0
  (148, 25)	2.3
  (149, 9)	1.0
  (149, 23)	5.9
  (149, 24)	27.0
  (149, 25)	1.8


## Splitting dataset into Training & Test set

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)
train_df = pd.read_csv( "American Express User Exit Prediction.csv")
test_df = pd.read_csv ("American Express User Exit Prediction.csv")

TypeError: ignored

## Feature Scaling

In [12]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

NameError: ignored

## ANN

### Initialization

In [ ]:
ann = tf.keras.models.Sequential()

### Adding input layer and first hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding second hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding output layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## ANN Training

### Compiling ANN

In [ ]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### Training on training dataset

In [ ]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 120)

NameError: ignored

# Predictions

### Single Prediction

In [ ]:
print(ann.predict(sc.transform([[0.0, 1.0, 0.0, 501, 0, 32, 2, 0.0, 4, 1, 545501]])) > 0.5)

NameError: ignored

### Predication on testset

In [ ]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

NameError: ignored

### Confusion Matrix

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

NameError: ignored